### ISSUE TITLE
获取的cookie有差异

### ISSUE THREAD

**Issue by ygrqmb** [KunCheng-He/hifini-sign-in#2]
老哥，我看你获取的cookie格式为：
bbs_sid=***
bbs_token=***
cookie_test=***
但是我这边获取cookie格式合着不一样。
Hm_lvt_*****=***,***,***,***;
 bbs_sid=***;
 bbs_token=***

按照我获取的cookie放到变量里面 跑起来提示：等待20秒后进行重试... 或者签到失败，失败原因:'NoneType' object has no attribute 'group'
HIFINI 签到结果 'NoneType' object has no attribute 'group'
请正确配置 cookie !!!

**Comment by KunCheng-He** [comment]
今天我发现网站我已经进不去了，不知道什么原因。

cookie格式有差异这个我还真不知道，请求一样的话应该可以返回。

上面的这个原因是对请求返回的内容进行正则表达式的匹配，结果没有匹配到内容。你拉取的是最新的代码吗？之前我也遇到这个问题，前天刚刚修改了一版正则表达式，如果是最新的，应该是还有的情况我没有考虑全面，如果你方便调试的话，欢迎提PR，共同完善。

**Comment by KunCheng-He** [comment]
我区域的宽带网络从昨天晚上开始进不去网站了，青龙面板所在服务器通过调试发现 cookie 直接失效了，导致所携带的 cookie 在请求首页时，返回的页面时未登录的页面，该页面没有包含人机验证的 sign 参数，所以正则表达式为匹配到内容，出现了 'NoneType' object has no attribute 'group'。

我的手机网络进入该网站正常，所以我通过手机网络重新登录后，更新了 cookie，现在我签到正常。我的cookie格式还是bbs_sid=。。。bbs_token=。。。

可以尝试更新 cookie 后试一下 @ygrqmb

**Comment by ygrqmb** [comment]
> 我区域的宽带网络从昨天晚上开始进不去网站了，青龙面板所在服务器通过调试发现 cookie 直接失效了，导致所携带的 cookie 在请求首页时，返回的页面时未登录的页面，该页面没有包含人机验证的 sign 参数，所以正则表达式为匹配到内容，出现了 'NoneType' 对象没有属性 'group'。
> 
> 我的手机网络进入该网站正常，所以我通过手机网络重新登录后，更新了 cookie，现在我签到正常。我的cookie格式还是bbs_sid=。。。bbs_token=。。。
> 
> 可以尝试更新 cookie 后试一下 @ygrqmb

感谢老哥，我刚刚测试了一下  可以使用了。不知道是不是昨天晚上 网站更新造成 今天凌晨没办法用。

**Comment by KunCheng-He** [comment]
OK，那我关闭Issue了，欢迎有问题来交流，如脚本有考虑不周的地方，欢迎PR。
