### ISSUE TITLE
无法签到了

### ISSUE THREAD

**Issue by for7GG** [KunCheng-He/hifini-sign-in#4]
网站应该又更新了，目前无法签到了 
签到失败，失败原因:'NoneType' object has no attribute 'group'
HIFINI 签到结果 'NoneType' object has no attribute 'group'
请正确配置 cookie !!!

**Comment by KunCheng-He** [comment]
@for7GG 好像网站防人机策略升级了，我看一下

**Comment by kgbaO** [comment]
大佬，什么时候，更新下脚本哈？

**Comment by KunCheng-He** [comment]
@kgbaO 最近比较忙，可能有点久哦，有点子的话欢迎贡献代码呀😁

**Comment by KunCheng-He** [comment]
@for7GG @kgbaO 已更新，可以试一下现在签到有没有问题，网站的人机策略没有更改，只是签到请求变动了，导致解析结果失败，之前的脚本应该也能签到成功，只是通知上是签到失败。
